# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ZFNPfip1bY42p3Wz8VGuLHnB3WRX_-A
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

model = joblib.load("california_housing_regression_model.pkl")

@app.route("/")
def home():
    return "California Housing Prediction API is running."

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()

    features = np.array([[
        data["MedInc"],
        data["HouseAge"],
        data["AveRooms"],
        data["AveBedrms"],
        data["Population"],
        data["AveOccup"],
        data["Latitude"],
        data["Longitude"]
    ]])

    prediction = model.predict(features)

    return jsonify({
        "predicted_house_value": float(prediction[0])
    })

if __name__ == "__main__":
    app.run()